name: mygardenai
description: A personal garden scanner and mapper.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.1.0
  syncfusion_flutter_calendar: ^24.2.9
  image: ^4.1.3
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.2
  sqflite: ^2.3.3
  path: ^1.8.3
  path_provider: ^2.1.2
  image_picker: ^1.0.4  # For custom map upload

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
